CREATE TABLE "xf_sepolia_payments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "xf_sepolia_payments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pixelX" integer NOT NULL,
	"pixelY" integer NOT NULL,
	"owner" varchar(256) NOT NULL,
	"amount" real NOT NULL,
	"nonce" varchar(256) NOT NULL,
	"paymentHash" varchar(256),
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "xf_sepolia_payments_nonce_unique" UNIQUE("nonce")
);
--> statement-breakpoint
CREATE TABLE "xf_sepolia_pixels" (
	"x" integer NOT NULL,
	"y" integer NOT NULL,
	"color" varchar(7) DEFAULT '#000000' NOT NULL,
	"owner" varchar(256) NOT NULL,
	"timestamp" timestamp with time zone NOT NULL,
	"price" real DEFAULT 0.01 NOT NULL,
	"updateCount" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "xf_sepolia_pixels_x_y_pk" PRIMARY KEY("x","y")
);
--> statement-breakpoint
CREATE INDEX "sepolia_payment_owner_idx" ON "xf_sepolia_payments" USING btree ("owner");--> statement-breakpoint
CREATE INDEX "sepolia_payment_nonce_idx" ON "xf_sepolia_payments" USING btree ("nonce");--> statement-breakpoint
CREATE INDEX "sepolia_pixel_owner_idx" ON "xf_sepolia_pixels" USING btree ("owner");--> statement-breakpoint
CREATE INDEX "sepolia_pixel_timestamp_idx" ON "xf_sepolia_pixels" USING btree ("timestamp");